name: Test PETSc with predefined matrix and vector
on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    container: ubuntu:22.04

    strategy:
      matrix:
        petsc_version: ["3.16.4", "3.16.5", "3.16.6", "3.17.0", "3.17.5", "3.18.5", "jolivet/fix-segfault-gamg"]
      fail-fast: false

    env:
      PETSC_ARCH: "linux-gnu-complex-32"
      PETSC_SLEPC_OPTFLAGS: "-O2"
      PETSC_SLEPC_MAKE_NP: 2
      PETSC_SLEPC_DEBUGGING: "yes"
      MPICH_CONFIGURE_OPTIONS: "FCFLAGS=-fallow-argument-mismatch FFLAGS=-fallow-argument-mismatch --with-device=ch4:ofi"  # See https://github.com/pmodels/mpich/issues/5811
      # MPICH_VERSION: 4.1
      PETSC_DIR: "/usr/local/petsc"
      PETSC_VERSION: ${{ matrix.petsc_version }}
      OPENBLAS_NUM_THREADS: 1
      OPENBLAS_VERBOSE: 0
      BUILD_NP: 2
    steps:
      - uses: actions/checkout@v3
         
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive && \
          apt-get -qq update && \
          apt-get -yq --with-new-pkgs -o Dpkg::Options::="--force-confold" upgrade && \
          apt-get -y install \
          clang \
          cmake \
          git \
          g++ \
          gfortran \
          libboost-dev \
          libboost-filesystem-dev \
          libboost-timer-dev \
          liblapack-dev \
          libopenblas-dev \
          ninja-build \
          pkg-config \
          python3-dev \
          python3-numpy \
          python3-pip \
          python3-scipy \
          python3-setuptools \
          wget && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      

      - name: Fetch PETSc
        run:
          git clone --single-branch --branch=${PETSC_VERSION} git@gitlab.com:petsc/petsc.git ${PETSC_DIR} 

      - name: Test gfortran
        run: |
          gfortran -fallow-argument-mismatch --version && \
          gcc -O2 --version

      - name: Install mpich
        run: |
          apt-get update && \
          apt-get -y install mpich
          apt-get clean && \
          rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      
      
      - name: Install MPI4py
        run: |
          export CC=mpicc
          pip3 install --no-cache-dir mpi4py 


      - name: Install PETSc
        run: |
          export CC=mpicc
          apt-get -qq update && \
          apt-get -y install bison flex && \
          # Complex, 32-bit int
          cd ${PETSC_DIR}/petsc
          python3 ./configure \
          PETSC_ARCH=linux-gnu-complex-32 \
          --COPTFLAGS="${PETSC_SLEPC_OPTFLAGS}" \
          --CXXOPTFLAGS="${PETSC_SLEPC_OPTFLAGS}" \
          --FOPTFLAGS="${PETSC_SLEPC_OPTFLAGS}" \
          --with-make-np=${PETSC_SLEPC_MAKE_NP} \
          --with-64-bit-indices=no \
          --with-debugging=${PETSC_SLEPC_DEBUGGING} \
          --with-fortran-bindings=no \
          --with-shared-libraries \
          --download-metis \
          --download-ptscotch \
          --download-scalapack \
          --download-suitesparse \
          --with-scalar-type=complex && \
          make PETSC_DIR=/usr/local/petsc PETSC_ARCH=linux-gnu-complex-32 ${MAKEFLAGS} all && \
          cd src/binding/petsc4py && \
          PETSC_ARCH=linux-gnu-complex-32 pip3 install --no-cache-dir .

      - name: Run problem (serial)
        run: python3 mwe.py
          
      - name: Run problem (parallel, 2 procs)
        run: mpirun -n 2 python3 mwe.py
          
      - name: Run problem (parallel, 3 procs)
        run: mpirun -n 3 python3 mwe.py
